### ISSUE TITLE
One-sentence summary

### ISSUE THREAD

**Issue by shouldsee** [CATH-summer-2017/De-Novo#6]
BTW, how would you summarize you objective in one sentence?

Can I describe it as "a classifier that checks whether a given CATH domain is from:
* a artificial De-novo, 
* a physical De-novo, 
* or a biological protein."

**Comment by ilsenatorov** [comment]
Right now I am just trying to find a way to find **all** De-Novo proteins in CATH. And after I do that I will try to figure out if De-Novo proteins need to be separated from biological ones
